import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import { TmaSDKLoader } from "@/components/TmaSDKLoader";

import "@/styles/globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }: PropsWithChildren) {
  return (
    <div className="h-screen flex flex-col bg-white">
      <header className="flex h-16 justify-center items-center bg-slate-900">
        <h3 className="font-sans font-bold text-white">
          AF PILOT INFLIGHT TOOL
        </h3>
      </header>
      <div className="flex flex-1 overflow-auto">{children}</div>
      <footer className="flex h-16 justify-end items-center pr-4 bg-slate-900">
        <p className="font-sans font-bold text-white">TerraNex42</p>
      </footer>
    </div>
  );
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head/>
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable)}>
        <TmaSDKLoader>
          <Layout>{children}</Layout>
        </TmaSDKLoader>
      </body>
    </html>
  );
}
